---
title: "Gadget model output"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), "model_files", 'model_output_figures.html')) })
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gadgetutils)
library(plotly)
library(DT)

## Example data
load("/Users/a22357/ownCloud/GadgetGhl/g3 runs/model_files_20220928/data/Fitted and optimized TMB model.rda")
```

Annual plot
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Catches

```{r}
ggplotly(plot_catch(fit) + 
           scale_fill_manual(
             values = c("ghl_female_imm" = "tomato1", 
                        "ghl_female_mat" = "tomato4", 
                        "ghl_male_imm" = "dodgerblue1", 
                        "ghl_male_mat" = "dodgerblue4"))
) %>% 
  plotly::layout(legend=list(x=0, y = 1, 
                             xanchor='left',
                             yanchor='bottom',
                             orientation='h')) 
```

### F

```{r}
ggplotly(plot_f(fit) +
           scale_fill_manual(
             values = c("ghl_female_imm" = "tomato1", 
                        "ghl_female_mat" = "tomato4", 
                        "ghl_male_imm" = "dodgerblue1", 
                        "ghl_male_mat" = "dodgerblue4")) + 
           theme(legend.position = "none")
)
```



Column {data-width=500}
-----------------------------------------------------------------------

### Recruitment

```{r}
ggplotly(plot_rec(fit) + 
           scale_fill_manual(
             values = c("ghl_female_imm" = "tomato1", 
                        "ghl_female_mat" = "tomato4", 
                        "ghl_male_imm" = "dodgerblue1", 
                        "ghl_male_mat" = "dodgerblue4")) + 
           theme(legend.position = "none"))
```

### Biomass

```{r}
ggplotly(plot_biomass(fit, plot_total = TRUE) + 
           scale_color_manual(
             values = c("ghl_female_imm" = "tomato1", 
                        "ghl_female_mat" = "tomato4", 
                        "ghl_male_imm" = "dodgerblue1", 
                        "ghl_male_mat" = "dodgerblue4",
                        "Total" = "black")) + 
           theme(legend.position = "none"))
```


Catch distributions 
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

```{r, echo = FALSE}
x <- plot_catchdist(fit, base_size = 14)
```

```{r, echo = FALSE, fig.height = 10, fig.width = 20, results='asis'}

for(i in seq_along(x)) {
  
  cat("  \n###",  names(x)[i], "  \n")
  print(x[[i]])
  cat("  \n")
}

```

Suitability
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

```{r, echo = FALSE}
x <- plot_suitability(fit, base_size = 14)
```

```{r, echo = FALSE, fig.height = 10, fig.width = 20, results='asis'}

for(i in seq_along(x)) {
  
  cat("  \n###",  names(x)[i], "  \n")
  print(x[[i]] + 
          theme(legend.position = "top") +
          scale_color_manual(
            values = c("ghl_female_imm" = "tomato1", 
                       "ghl_female_mat" = "tomato4", 
                       "ghl_male_imm" = "dodgerblue1", 
                       "ghl_male_mat" = "dodgerblue4"))
  )
  cat("  \n")
}

```

Maturity 
=======================================================================

```{r}
x <- plot_maturity(fit, stocks = "separate")

plotly::subplot(lapply(x, function(k) {
  k + scale_color_manual(
    values = c("ghl_female_imm" = "tomato1", 
               "ghl_female_mat" = "tomato4", 
               "ghl_male_imm" = "dodgerblue1", 
               "ghl_male_mat" = "dodgerblue4")) +
    theme(legend.position = "none")
}),
nrows = 2
)
```

Growth 
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

```{r, echo = FALSE}
x <- plot_growth(fit, base_size = 14)
```

```{r, echo = FALSE, fig.height = 10, fig.width = 20, results='asis'}

for(i in seq_along(x)) {
  
  cat("  \n###",  names(x)[i], "  \n")
  print(x[[i]])
  cat("  \n")
}
```


Survey indices
=======================================================================

Catches
=======================================================================

Age composition 
=======================================================================

Residuals
=======================================================================

Optimized parameters
=======================================================================

```{r}
DT::datatable(fit$params, options = list(pageLength = 500)) %>%
  DT::formatRound(columns=c('value'), digits=3)
```

